services:
    utility_master_vendor.dummy:
      class: Utility\MasterVendorBundle\Services\DummyService
#    utility_master_vendor.example:
#        class: Utility\MasterVendorBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]
